/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthedSplitRouteImport } from './routes/_authed/split'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as ApiDownloadVodIdRouteImport } from './routes/api/download.$vodId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedWatchVideoIdRouteImport } from './routes/_authed/watch.$videoId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSplitRoute = AuthedSplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiDownloadVodIdRoute = ApiDownloadVodIdRouteImport.update({
  id: '/api/download/$vodId',
  path: '/api/download/$vodId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWatchVideoIdRoute = AuthedWatchVideoIdRouteImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthedSettingsRoute
  '/split': typeof AuthedSplitRoute
  '/api/health': typeof ApiHealthRoute
  '/watch/$videoId': typeof AuthedWatchVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/$vodId': typeof ApiDownloadVodIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof AuthedSettingsRoute
  '/split': typeof AuthedSplitRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AuthedIndexRoute
  '/watch/$videoId': typeof AuthedWatchVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/$vodId': typeof ApiDownloadVodIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/split': typeof AuthedSplitRoute
  '/api/health': typeof ApiHealthRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/watch/$videoId': typeof AuthedWatchVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/$vodId': typeof ApiDownloadVodIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/split'
    | '/api/health'
    | '/watch/$videoId'
    | '/api/auth/$'
    | '/api/download/$vodId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/split'
    | '/api/health'
    | '/'
    | '/watch/$videoId'
    | '/api/auth/$'
    | '/api/download/$vodId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/settings'
    | '/_authed/split'
    | '/api/health'
    | '/_authed/'
    | '/_authed/watch/$videoId'
    | '/api/auth/$'
    | '/api/download/$vodId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDownloadVodIdRoute: typeof ApiDownloadVodIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/split': {
      id: '/_authed/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof AuthedSplitRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/download/$vodId': {
      id: '/api/download/$vodId'
      path: '/api/download/$vodId'
      fullPath: '/api/download/$vodId'
      preLoaderRoute: typeof ApiDownloadVodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/watch/$videoId': {
      id: '/_authed/watch/$videoId'
      path: '/watch/$videoId'
      fullPath: '/watch/$videoId'
      preLoaderRoute: typeof AuthedWatchVideoIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedSplitRoute: typeof AuthedSplitRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedWatchVideoIdRoute: typeof AuthedWatchVideoIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedSplitRoute: AuthedSplitRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedWatchVideoIdRoute: AuthedWatchVideoIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDownloadVodIdRoute: ApiDownloadVodIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
